### ISSUE TITLE
Quality ranking

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-indexer#11]
catchall issue for thoughts on quality + relevance across different datasets
- incorporating extrinsic/source-specific signals (likes, comments, position in original results for query, etc) -- how to normalize these?
- intrinsic signals (?)

**Comment by autoencoder** [comment]
Normalizing - Quickest easiest way to start: Already have a basic hyper-parameter optimizer setup in the Indexer for dedupe tasks. If we can find or create a query relevancy ratings dataset (e.g. [#1](https://github.com/mediachain/mediachain-indexer-frontend/issues/1)?), then we can hook this up to the hyper-parameter optimizer for search too.

**Comment by parkan** [comment]
Sounds like there's some fairly discrete dataset work here, feel free to plan that out and assign as you see fit. I am down to help

**Comment by parkan** [comment]
I think this is at least partially covered through the quality models + unsplash classifier, closing
