### ISSUE TITLE
Explore wheel-based distribution

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-indexer#15]
Distributing this via pip is v hard and probably won't get better with newer models incorporated, consider wheel/binary distribution

**Comment by autoencoder** [comment]
Looking into 3 solutions now:
- Git submodules to include specific dependency versions & compile manually
- Wheel
- Docker

**Comment by parkan** [comment]
We used submodules for a bit, I kind of feel like I'm their biggest proponent and I _still_ hate them. At minimum need hook to automatically `git submodule update --init` on changes to `.gitmodules` (no idea why this isn't the default, I guess maybe for larger repos?)

**Comment by parkan** [comment]
Closing for now since redistributing indexer is not a v high priority
