### ISSUE TITLE
latest_ref field name is misleading

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-indexer#26]
If I were to guess, `latest_ref` sounds like it refers to the latest ref in the object chain, aka the head, while it is in fact the most recent `raw_ref` to be applied.

Should either rename it (for the benefit of the medium devs, for ex.) or apply the more comprehensive solution where we have multiple raw refs in the final folded form (I think it can just be  a chronological list but @autoencoder had some other thoughts?)

**Comment by autoencoder** [comment]
Nothing in the Indexer really depends on `latest_ref` at the moment, so feel free to rewrite / rename that in whatever way makes the most sense.
