### ISSUE TITLE
Sample image used in medium post disappeared

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-indexer#35]
The sample image from this post https://medium.com/@parkan/mediachain-testnet-supplemental-b4ad6bfc05b4

No longer appears to be in the indexer:

http://images.mediachain.io/image/QmULPNnUEr5MhyZCeGTXxpizTPRJEq9o7HvgeH184H4S5M

Not showing up in search results:

http://images.mediachain.io/search/luxurious%20velvet%20cloak

Did something get rebuilt w/o it? Can still pull actual image with `mediachain get`

**Comment by parkan** [comment]
@denisnazarov please share your js dev environment before you leave next time :|

**Comment by denisnazarov** [comment]
@parkan any specific problems you were having?

**Comment by parkan** [comment]
@denisnazarov yeah the frontend was crashing on the sample image from the blog post (member access on `undefed` in the tags module) and I couldn't really diagnose it well w/o source maps

**Comment by autoencoder** [comment]
Closing as the initial backend<->frontend compatibility issue was fixed, and we'll be replacing the Getty images in testnet shortly.
